version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-homework16
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_rahasia
      MYSQL_DATABASE: initial_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - mysql_network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge